# Generated by Django 5.1.2 on 2024-10-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0003_predictionhistory_user_alter_predictionhistory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cure', models.TextField()),
                ('care_recommendations', models.TextField()),
            ],
        ),
    ]
